# =========================
# Telegram Message Analysis Config
# =========================

# Message Fetching Settings
# -------------------------
# Settings related to fetching messages from Telegram
message_fetching:
  default_limit: 100  # Default number of messages to fetch

# AI Model Settings
# ----------------
# Settings for AI model usage and configuration
ai:
  model: "deepseek-r1"  # Model to use for summarization
  claude_model: "claude-3-5-sonnet-latest"

  claude_output_tokens: 2048
  # General summary prompt (kept for backward compatibility)
  summary_prompt: >
    Analyze the following Telegram chat messages and create a concise summary organized by participants. 
    Here are the messages:

    {messages}
  
  # Overall summary prompt for conversation analysis
  overall_prompt: >
    Extract a list of all projects, cryptocurrencies, or platforms mentioned in these Telegram chat messages.
    
    {messages}
  
  # Participant-specific summary prompt
  participant_prompt: >
    Create a very brief summary (2-4 sentences maximum) of {participant}'s key messages in this chat.
    Focus only on substantive content about projects, opinions, or strategies they mentioned.
    
    
    {messages}

# Telegram Client Settings
# -----------------------
# Configuration for the Telegram client
telegram_client:
  system_version: "4.16.30-vxCUSTOM"
  app_version: "1.0.0"
  device_model: "iPhone 15 Pro Max"
  system_lang_code: "en"
  lang_code: "en" 
